### ISSUE TITLE
WString.cpp fails to build with gcc 8.3

### ISSUE THREAD

**Issue by dave4445** [arduino/ArduinoCore-samd#555]
Newer gcc, better warnings, catching questionable code:

../ArduinoCore-samd/cores/arduino/WString.cpp: In member function 'void String::remove(unsigned int, unsigned int)':
../ArduinoCore-samd/cores/arduino/WString.cpp:701:9: error: 'char* strncpy(char*, const char*, size_t)' accessing 0 or more bytes at offsets [0, 2147483647] and [0, 2147483647] may overlap up to 4294967295 bytes at offset [6442450941, 2147483647] [-Werror=restrict]
  strncpy(writeTo, buffer + index + count,len - index);
  ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

strncpy() is not safe when src and dst overlap.  Changing this to memmove() is more appropriate:



diff --git a/cores/arduino/WString.cpp b/cores/arduino/WString.cpp
index 4c01559..08e91d6 100644
--- a/cores/arduino/WString.cpp
+++ b/cores/arduino/WString.cpp
@@ -698,7 +698,7 @@ void String::remove(unsigned int index, unsigned int count){
        if (count > len - index) { count = len - index; }
        char *writeTo = buffer + index;
        len = len - count;
-       strncpy(writeTo, buffer + index + count,len - index);
+       memmove(writeTo, buffer + index + count,len - index);
        buffer[len] = 0;
 }

**Comment by facchinm** [comment]
Fixed in https://github.com/arduino/ArduinoCore-API/blob/master/api/String.cpp#L693 , marking to be closed when we'll finally merge the `api` branch
